ALTER TABLE hub.municipios ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE hub.municipios ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE hub.liderancas ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE hub.liderancas ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE hub.assessores ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE hub.assessores ADD COLUMN IF NOT EXISTS longitude NUMERIC;
